// Auto-generated by @farming-labs/next — do not edit manually.

import docsConfig from "@/docs.config";
import type { GeneratedChangelogEntry } from "@farming-labs/next/changelog";
import {
  createNextChangelogIndexMetadata,
  createNextChangelogIndexPage,
} from "@farming-labs/next/changelog";

export const changelogEntries: GeneratedChangelogEntry[] = [

];

export const metadata = createNextChangelogIndexMetadata(docsConfig);

const ChangelogPage = createNextChangelogIndexPage(docsConfig, changelogEntries);

export default ChangelogPage;
