// Auto-generated by @farming-labs/next — do not edit manually.

import docsConfig from "@/docs.config";
import type { GeneratedChangelogEntry } from "@farming-labs/next/changelog";
import {
  createNextChangelogEntryMetadata,
  createNextChangelogEntryPage,
  createNextChangelogStaticParams,
} from "@farming-labs/next/changelog";

export const changelogEntries: GeneratedChangelogEntry[] = [

];

export const generateStaticParams = createNextChangelogStaticParams(changelogEntries);
export const generateMetadata = createNextChangelogEntryMetadata(docsConfig, changelogEntries);

const ChangelogEntryPage = createNextChangelogEntryPage(docsConfig, changelogEntries);

export default ChangelogEntryPage;
