import * as fs from "node:fs";
import * as path from "node:path";
import * as zlib from "node:zlib";

const rootDir = process.cwd();
const wasmCandidates = [
  path.resolve(rootDir, "packages/renderer/src/wasm/resvg.wasm"),
  path.resolve(rootDir, "node_modules/.pnpm/next@16.3.8_@babel+core@7.29.7_supports-color@7.2.0__@playwright+test@1.64.0_@types+nod_4ef4fb8b8e97382e90bc1efb968de5cd/node_modules/next/dist/compiled/@vercel/og/resvg.wasm"),
];

let wasmPath = wasmCandidates.find(p => fs.existsSync(p));

if (!wasmPath) {
  console.error("[embed-resvg-wasm] Error: resvg.wasm not found");
  process.exit(1);
}

const wasmBuf = fs.readFileSync(wasmPath);
const gz = zlib.gzipSync(wasmBuf, { level: 9 });
const b64 = gz.toString("base64");

const outFile = path.resolve(rootDir, "packages/renderer/src/wasm-data.ts");
const code = `// Auto-generated by scripts/embed-resvg-wasm.ts. Do not edit directly.
export const RESVG_WASM_GZIP_BASE64 = "${b64}";
`;

fs.writeFileSync(outFile, code);
console.log(`[embed-resvg-wasm] Successfully embedded resvg.wasm (${wasmBuf.length} bytes -> ${b64.length} base64 chars) into ${outFile}`);
