import * as fs from 'node:fs';
import * as path from 'node:path';

const rootDir = process.cwd();
const distDir = path.resolve(rootDir, 'apps/canvas-web/dist');
const outFile = path.resolve(rootDir, 'packages/sync/src/embedded-canvas.ts');

const MIME_TYPES: Record<string, string> = {
  '.html': 'text/html; charset=utf-8',
  '.js': 'application/javascript; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.svg': 'image/svg+xml',
  '.json': 'application/json',
  '.png': 'image/png',
  '.ico': 'image/x-icon',
  '.webp': 'image/webp',
  '.woff2': 'font/woff2',
  '.woff': 'font/woff',
  '.ttf': 'font/ttf',
};

const TEXT_EXTS = new Set(['.html', '.js', '.css', '.svg', '.json', '.map']);

function collectFiles(dir: string, baseDir: string = dir): string[] {
  if (!fs.existsSync(dir)) return [];
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  const files: string[] = [];
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...collectFiles(fullPath, baseDir));
    } else {
      files.push(fullPath);
    }
  }
  return files;
}

export function generateEmbeddedCanvas(): void {
  if (!fs.existsSync(distDir)) {
    console.warn(`[embed-canvas] dist directory does not exist: ${distDir}`);
    fs.writeFileSync(
      outFile,
      `// Auto-generated fallback - run scripts/embed-canvas.ts after building canvas-web\n` +
      `export interface EmbeddedAsset {\n  contentType: string;\n  data: string;\n  isBase64: boolean;\n}\n\n` +
      `export const EMBEDDED_CANVAS_ASSETS: Record<string, EmbeddedAsset> = {};\n`
    );
    return;
  }

  const allFiles = collectFiles(distDir);
  const assets: Record<string, { contentType: string; data: string; isBase64: boolean }> = {};

  for (const filePath of allFiles) {
    const relPath = '/' + path.relative(distDir, filePath).replace(/\\/g, '/');
    const ext = path.extname(filePath).toLowerCase();
    const contentType = MIME_TYPES[ext] || 'application/octet-stream';
    const isText = TEXT_EXTS.has(ext);

    if (isText) {
      const text = fs.readFileSync(filePath, 'utf-8');
      assets[relPath] = { contentType, data: text, isBase64: false };
    } else {
      const buffer = fs.readFileSync(filePath);
      assets[relPath] = { contentType, data: buffer.toString('base64'), isBase64: true };
    }
  }

  const content = `// Auto-generated by scripts/embed-canvas.ts - DO NOT EDIT MANUALLY
export interface EmbeddedAsset {
  contentType: string;
  data: string;
  isBase64: boolean;
}

export const EMBEDDED_CANVAS_ASSETS: Record<string, EmbeddedAsset> = ${JSON.stringify(assets, null, 2)};
`;

  fs.writeFileSync(outFile, content, 'utf-8');
  console.log(`[embed-canvas] Embedded ${Object.keys(assets).length} files into ${outFile}`);
}

generateEmbeddedCanvas();
